# O nome abaixo deve ser IGUAL ao que está no seu dbt_project.yml (campo 'profile:')
cotacao_profile:
  outputs:
    dev:
      type: postgres
      host: postgres        # Nome do serviço no seu docker-compose.yaml
      user: airflow         # Usuário que você definiu no Docker
      password: airflow     # Senha que você definiu no Docker
      port: 5432
      dbname: airflow       # Nome do banco de dados no Docker
      schema: public
      threads: 4
  target: dev