table PlanoContas
	lineageTag: a3dd64cb-0423-4825-ae2c-c1b5b182c36c

	column ID_Conta
		dataType: int64
		formatString: 0
		lineageTag: 382b9f06-6379-4b55-8911-104127825ed1
		summarizeBy: none
		sourceColumn: ID_Conta

		annotation SummarizationSetBy = Automatic

	column 'Tipo Relatório'
		dataType: string
		lineageTag: 23451d46-5705-4930-9ffa-26c4e43da47b
		summarizeBy: none
		sourceColumn: Tipo Relatório

		annotation SummarizationSetBy = Automatic

	column 'Conta Nível 1'
		dataType: string
		lineageTag: 9a1da4bd-9432-4e87-b857-528e4a4b3529
		summarizeBy: none
		sourceColumn: Conta Nível 1

		annotation SummarizationSetBy = Automatic

	column 'Conta Nível 2'
		dataType: string
		lineageTag: b0196c23-f99f-4315-bcbf-34bcd982968b
		summarizeBy: none
		sourceColumn: Conta Nível 2

		annotation SummarizationSetBy = Automatic

	column 'Conta Nível 3'
		dataType: string
		lineageTag: b4e34d16-10b0-4fc7-8542-134b0ea04e56
		summarizeBy: none
		sourceColumn: Conta Nível 3

		annotation SummarizationSetBy = Automatic

	column 'Conta Nível 4'
		dataType: string
		lineageTag: 9e0fbe02-752c-4459-8d35-c0ea7ee6602e
		summarizeBy: none
		sourceColumn: Conta Nível 4

		annotation SummarizationSetBy = Automatic

	partition PlanoContas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\mdant\OneDrive\Documents\Estudo Power BI\DataScienceAcademy\Mini-Projetos\área-contabil\Dataset.xlsx"), null, true),
				    PlanoContas_Sheet = Fonte{[Item="PlanoContas",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(PlanoContas_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Conta", Int64.Type}, {"Tipo Relatório", type text}, {"Conta Nível 1", type text}, {"Conta Nível 2", type text}, {"Conta Nível 3", type text}, {"Conta Nível 4", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

