table DadosFinanceiros
	lineageTag: 70fcdb7d-b671-42cb-b341-aa24ce34c205

	column Tipo
		dataType: string
		lineageTag: 91f7ad77-505c-4195-bc18-310765bdd348
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Componente
		dataType: string
		lineageTag: faa89489-28e2-4698-a4ea-d395d05e5f5a
		summarizeBy: none
		sourceColumn: Componente

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc14d985-f9fe-416a-a582-d92530e84ced
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 72ec1812-a7f0-4ba4-9b7f-6c8426d93e54
			defaultHierarchy: LocalDateTable_0c23ccff-0c51-492e-9786-65a27bbf7e6f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valor
		dataType: double
		lineageTag: 3f0442bc-8686-4235-bc4e-760d16b1e3cf
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DadosFinanceiros = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\mdant\OneDrive\Documents\Estudo Power BI\DataScienceAcademy\Mini-Projetos\área-financeira\DadosFinanceiros.xlsx"), null, true),
				    DadosFinanceiros_Sheet = Fonte{[Item="DadosFinanceiros",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(DadosFinanceiros_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Tipo", type text}, {"Componente", type text}, {"01/01/2019", Int64.Type}, {"01/02/2019", type number}, {"01/03/2019", type number}, {"01/04/2019", Int64.Type}, {"01/05/2019", type number}, {"01/06/2019", Int64.Type}, {"01/07/2019", Int64.Type}, {"01/08/2019", Int64.Type}, {"01/09/2019", Int64.Type}, {"01/10/2019", Int64.Type}, {"01/11/2019", Int64.Type}, {"01/12/2019", Int64.Type}, {"01/01/2020", Int64.Type}, {"01/02/2020", Int64.Type}, {"01/03/2020", Int64.Type}, {"01/04/2020", Int64.Type}, {"01/05/2020", Int64.Type}, {"01/06/2020", Int64.Type}, {"01/07/2020", Int64.Type}, {"01/08/2020", Int64.Type}, {"01/09/2020", Int64.Type}, {"01/10/2020", Int64.Type}, {"01/11/2020", Int64.Type}, {"01/12/2020", Int64.Type}, {"01/01/2022", Int64.Type}, {"01/02/2022", Int64.Type}, {"01/03/2022", Int64.Type}, {"01/04/2022", Int64.Type}, {"01/05/2022", Int64.Type}, {"01/06/2022", Int64.Type}, {"01/07/2022", Int64.Type}, {"01/08/2022", Int64.Type}, {"01/09/2022", Int64.Type}, {"01/10/2022", Int64.Type}, {"01/11/2022", Int64.Type}, {"01/12/2022", Int64.Type}}),
				    #"Tabela Transposta" = Table.UnpivotOtherColumns(#"Tipo Alterado1", {"Tipo", "Componente"}, "Data", "Valor"),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Tabela Transposta",{{"Data", type date}})
				in
				    #"Tipo Alterado2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

