table Medidas
	lineageTag: adb91fcf-5f4d-40c9-9769-b5e818f9711d

	measure TotalReceitas =
			CALCULATE(
			    SUM(DadosFinanceiros[Valor]),
			    DadosFinanceiros[Tipo] = "Receitas"
			)
		lineageTag: e758a3c8-5603-4995-88ec-45ed4372d362

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalDespesas =
			CALCULATE(
			    SUM(DadosFinanceiros[Valor]),
			    DadosFinanceiros[Tipo] = "Despesas"
			)
		lineageTag: d163f512-0e91-4c6a-a8e4-2cb45dee972d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Lucro = [TotalReceitas] - [TotalDespesas]
		lineageTag: f80c2bed-fcc1-4289-9083-df069dba670c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MargemLucro = DIVIDE([Lucro], [TotalReceitas], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 55ae9c4e-f0b9-4612-894e-b0fa29b4b5a7

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

