version: 2

models:
  - name: fct_vendas_categoria
    description: "Tabela agregada de vendas por categoria e período"
    columns:
      - name: categoria
        tests:
          - not_null
      - name: receita_total
        description: "Soma do valor das vendas"
        tests:
          - not_null
      - name: qtd_pedidos
        tests:
          - dbt_utils.accepted_range:
              arguments:
                min_value: 1 # Garante que não temos categorias com zero vendas
  - name: avg_ticket_cliente
    description: "Tabela para métrica de Ticket Médio por Cliente"
    columns:
      - name: cliente_id
        tests:
          - not_null
      - name: ticket_medio
        description: "Média dos valores por cliente"
        tests:
          - not_null
  - name: fct_vendas_por_produto
    description: "Tabela agregada de vendas por nome de produto"
    columns:
      - name: nome_produto
        tests:
          - not_null
      - name: receita_total
        description: "Soma do valor das vendas"
        tests:
          - not_null
