name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

# Este nome 'profile' deve ser IGUAL ao nome no topo do profiles.yml
profile: 'ecommerce_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_analytics:
    gold:
      +materialized: table
    staging:
      +materialized: view

vars:
  dbt_utils_dispatch_list: ['dbt_utils']

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_utils']